feat(jupiter): add some javadoc
gravitee-io/gravitee-gateway-api pull request #106
Opened 2022-04-27 15:32 UTC by jhaeyaert

**Description**

Add some javadoc

2022-04-29 07:53 UTC, guillaumelamirand commented on src/main/java/io/gravitee/gateway/reactive/api/context/ExecutionContext.java
>      <T> T getInternalAttribute(String name);
How those methods arround internal attribute are hidden from user perspective ?

2022-04-29 07:56 UTC, guillaumelamirand requested changes
Perfect, just one question regarding internal attributes.

2022-05-02 12:22 UTC, jhaeyaert commented on src/main/java/io/gravitee/gateway/reactive/api/context/ExecutionContext.java
>      <T> T getInternalAttribute(String name);
They simply not be displayed (ex: debug mode) and policy will just have access to attributes (not internal).

2022-05-02 12:50 UTC, guillaumelamirand approved these changes

2022-05-02 12:50 UTC, merged