WIP -- skipCI --
gravitee-io/gravitee-gateway-api pull request #128
Opened 2022-07-29 06:36 UTC by marcambier

**Issue**

https://github.com/gravitee-io/issues/issues/7991

**Description**

:warning: WIP :warning:

2022-08-12 16:22 UTC, jhaeyaert requested changes
Some comment about naming. I let you consider them or leave with it if not pertinent.

2022-08-16 07:19 UTC, marcambier commented on src/main/java/io/gravitee/gateway/jupiter/api/policy/SecurityToken.java
> +        EMPTY,
Yes, I used NONE :+1:

2022-08-16 07:19 UTC, marcambier commented on src/main/java/io/gravitee/gateway/jupiter/api/policy/SecurityToken.java
> +    private SecurityToken(TokenType tokenType, String tokenValue) {
Nice catch, I turned it into a string

2022-08-16 07:20 UTC, merged

2022-08-16 07:22 UTC, graviteeio commented
:tada: This PR is included in version 1.39.0 :tada:

The release is available on:
- `1.39.0`
- [GitHub release](https://github.com/gravitee-io/gravitee-gateway-api/releases/tag/1.39.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: