feat: handle stop on entrypoint connector
gravitee-io/gravitee-gateway-api pull request #151
Opened 2022-10-03 08:32 UTC by jhaeyaert

**Issue**

https://graviteecommunity.atlassian.net/browse/APIM-92

**Description**

Implement common way send stop hook to entrypoint connectors.

---
**Gravitee.io Automatic Deployment**

🚀 A prerelease version of this package has been published on Gravitee's private artifactory, you can:
 - use it directly by updating your project with version: `1.48.0-apim-92-entrypoint-lifecycle-stop-SNAPSHOT`
 - download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gateway/gravitee-gateway-api/1.48.0-apim-92-entrypoint-lifecycle-stop-SNAPSHOT/gravitee-gateway-api-1.48.0-apim-92-entrypoint-lifecycle-stop-SNAPSHOT.zip)

2022-10-03 11:44 UTC, guillaumelamirand requested changes

2022-10-03 16:39 UTC, jhaeyaert commented on src/main/java/io/gravitee/gateway/jupiter/api/connector/entrypoint/async/EntrypointAsyncConnector.java
> +        this.stopHook = BehaviorProcessor.create();
Done.
Just to have a good understanding, is it a good practice or doo you see any issue with that ?

2022-10-03 16:41 UTC, jhaeyaert commented on src/main/java/io/gravitee/gateway/jupiter/api/connector/entrypoint/async/EntrypointAsyncConnector.java
> +    protected <R> FlowableTransformer<R, R> mergeWithFirst(Flowable<R> other) {
Moved to gravitee-common, please, have a look here https://github.com/gravitee-io/gravitee-common/pull/78

2022-10-04 10:02 UTC, guillaumelamirand commented on src/main/java/io/gravitee/gateway/jupiter/api/connector/entrypoint/async/EntrypointAsyncConnector.java
> +        this.stopHook = BehaviorProcessor.create();
It is more about visibility and clarity because actually after compilation field instanciation is transformed to constructor. Also as BehaviorProcessor.create(); is the default value that make sense to me to set it directly on the field. a bit subjectif I would say

2022-10-04 10:02 UTC, guillaumelamirand approved these changes

2022-10-04 12:00 UTC, merged