feat: add deployment context to connector factory
gravitee-io/gravitee-gateway-api pull request #160
Opened 2022-11-14 14:04 UTC by jhaeyaert

**Issue**

https://graviteecommunity.atlassian.net/browse/APIM-266

**Description**

Add a deployment context object to pass to connector factory in order to get access to useful component such as api, services, ...

---
**Gravitee.io Automatic Deployment**

🚀 A prerelease version of this package has been published on Gravitee's private artifactory, you can:
 - use it directly by updating your project with version: `2.0.0-apim-266-http-proxy-connectors-SNAPSHOT`
 - download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gateway/gravitee-gateway-api/2.0.0-apim-266-http-proxy-connectors-SNAPSHOT/gravitee-gateway-api-2.0.0-apim-266-http-proxy-connectors-SNAPSHOT.zip)

2022-11-14 14:14 UTC, ytvnr commented on src/main/java/io/gravitee/gateway/jupiter/api/context/DeploymentContext.java
> +     *
maybe we can provide some examples of components to retrieve ?

2022-11-14 14:15 UTC, jhaeyaert commented on src/main/java/io/gravitee/gateway/jupiter/api/context/DeploymentContext.java
> +     *
As it is more an implementation consideration it should not imho.

2022-11-16 17:15 UTC, guillaumelamirand requested changes

2022-11-16 17:15 UTC, guillaumelamirand commented on src/main/java/io/gravitee/gateway/jupiter/api/connector/ConnectorFactory.java
> +     * Allows creating new connector from the given string configuration.
```suggestion
     * Allow creating new connector from the given string configuration.
```
Allow was right actually. It is imperative.

2022-11-16 17:15 UTC, guillaumelamirand commented on src/main/java/io/gravitee/gateway/jupiter/api/connector/entrypoint/async/EntrypointAsyncConnectorFactory.java
> +     * Allows creating new connector from the given string configuration and QoS (Quality Of Service).
```suggestion
     * Allow creating new connector from the given string configuration and QoS (Quality Of Service).
```

2022-11-16 17:15 UTC, guillaumelamirand commented on src/main/java/io/gravitee/gateway/api/ExecutionContext.java
> +     * Skip security chain isn't prefixed to avoid breaking code where this constant isn't used.
As we are building the v4, shouldn't we start from a fresh/clean implementation without so much care about the legacy??

2022-11-16 17:15 UTC, guillaumelamirand commented on src/main/java/io/gravitee/gateway/jupiter/api/context/DeploymentContext.java
> +public interface DeploymentContext {
Could you add some details here regarding the usage of DeploymentContext in opposite to ExecutionContext?

2022-11-16 17:20 UTC, jhaeyaert commented on src/main/java/io/gravitee/gateway/api/ExecutionContext.java
> +     * Skip security chain isn't prefixed to avoid breaking code where this constant isn't used.
I have created this attribute specifically for being able to not use it anymore 😜
In fact, no constant were defined (just string here and there) and I needed to support moving from the old attribute to the new internal attribute (have a look at the `ExecutionContextAdapter`).

2022-11-16 17:23 UTC, jhaeyaert commented on src/main/java/io/gravitee/gateway/jupiter/api/context/DeploymentContext.java
> +public interface DeploymentContext {
Done!

2022-11-18 08:28 UTC, guillaumelamirand commented on src/main/java/io/gravitee/gateway/api/ExecutionContext.java
> +     * Skip security chain isn't prefixed to avoid breaking code where this constant isn't used.
Ok I got it perfect !

2022-11-18 08:31 UTC, guillaumelamirand approved these changes

2022-11-18 08:32 UTC, merged

2022-11-18 08:35 UTC, graviteeio commented
:tada: This PR is included in version 2.0.0-alpha.4 :tada:

The release is available on:
- `2.0.0-alpha.4`
- [GitHub release](https://github.com/gravitee-io/gravitee-gateway-api/releases/tag/2.0.0-alpha.4)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-12-09 12:22 UTC, graviteeio commented
:tada: This PR is included in version 2.0.0 :tada:

The release is available on:
- `2.0.0`
- [GitHub release](https://github.com/gravitee-io/gravitee-gateway-api/releases/tag/2.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: