feat: introduce new interfaces for native api support
gravitee-io/gravitee-gateway-api pull request #241
Opened 2024-10-17 07:30 UTC by phiz71

**Issue**

https://gravitee.atlassian.net/browse/APIM-7109

**Description**

TBD

2024-10-17 16:27 UTC, jhaeyaert requested changes

2024-10-17 16:27 UTC, jhaeyaert commented on src/main/java/io/gravitee/gateway/api/service/ApiKeyService.java
> +     * Get api key by its api and key.
by its api and md5 hash of the key.

2024-10-17 16:27 UTC, jhaeyaert commented on src/main/java/io/gravitee/gateway/reactive/api/context/kafka/KafkaConnectionContext.java
> +    void setCallbacks(Callback[] callbacks);
Should move on internal context imho.

2024-10-17 16:27 UTC, jhaeyaert commented on src/main/java/io/gravitee/gateway/reactive/api/context/kafka/KafkaConnectionContext.java
> +    Callback[] callbacks();
Probably good to add a piece of doc on it to explain its purpose.

2024-10-17 16:27 UTC, jhaeyaert commented on src/main/java/io/gravitee/gateway/reactive/api/policy/kafka/KafkaSecurityPolicy.java
> +    Completable authenticate(final KafkaConnectionContext ctx);
I think it would be good to add some javadoc explaining how the token can be extracted and what is expected to be implemented by the authenticate.

2024-10-18 08:12 UTC, jhaeyaert approved these changes

2024-10-18 09:15 UTC, ThibaudAV approved these changes

2024-10-18 09:31 UTC, merged

2024-10-18 09:34 UTC, graviteeio commented
:tada: This PR is included in version 3.9.0-alpha.5 :tada:

The release is available on:
- `3.9.0-alpha.5`
- [GitHub release](https://github.com/gravitee-io/gravitee-gateway-api/releases/tag/3.9.0-alpha.5)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-12-30 10:37 UTC, graviteeio commented
:tada: This PR is included in version 3.9.0 :tada:

The release is available on:
- `3.9.0`
- [GitHub release](https://github.com/gravitee-io/gravitee-gateway-api/releases/tag/3.9.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: