feat: add TemplateEngine for KafkaConnectionContext
gravitee-io/gravitee-gateway-api pull request #261
Opened 2024-11-29 16:13 UTC by ThibaudAV

**Issue**

https://github.com/gravitee-io/issues/issues/XXXXX

**Description**

A small description of what you did in that PR.

**Additional context**

2024-11-29 16:25 UTC, jhaeyaert requested changes

2024-11-29 16:25 UTC, jhaeyaert commented on src/main/java/io/gravitee/gateway/reactive/api/context/kafka/KafkaConnectionContext.java
> +    String TEMPLATE_ATTRIBUTE_CONTEXT = "context";
I would rather move HttpPlainExecutionContext.TEMPLATE_ATTRIBUTE_CONTEXT to BaseExecutionContext so it is inherited by all the sub interfaces and not duplicated. wdyt?

2024-11-29 16:29 UTC, ThibaudAV commented on src/main/java/io/gravitee/gateway/reactive/api/context/kafka/KafkaConnectionContext.java
> +    String TEMPLATE_ATTRIBUTE_CONTEXT = "context";
yes 🚀

2024-11-29 16:32 UTC, jhaeyaert approved these changes

2024-11-29 16:35 UTC, merged

2024-11-29 16:38 UTC, graviteeio commented
:tada: This PR is included in version 3.9.0-alpha.22 :tada:

The release is available on:
- `3.9.0-alpha.22`
- [GitHub release](https://github.com/gravitee-io/gravitee-gateway-api/releases/tag/3.9.0-alpha.22)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-12-30 10:36 UTC, graviteeio commented
:tada: This PR is included in version 3.9.0 :tada:

The release is available on:
- `3.9.0`
- [GitHub release](https://github.com/gravitee-io/gravitee-gateway-api/releases/tag/3.9.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: